test link checker
networkservicemesh/deployments-k8s pull request #4116
Opened 2021-12-20 13:11 UTC by Mixaster995

Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>

2021-12-22 21:24 UTC, denis-tingaikin commented on .github/workflows/ci.yaml
> +      image: lycheeverse/lychee:latest
Please use the fixed version.

2021-12-22 21:24 UTC, denis-tingaikin commented on .github/workflows/ci.yaml
> +          done
```suggestion
```

2021-12-22 21:25 UTC, denis-tingaikin commented on .github/workflows/ci.yaml
> +          lychee -v '**/*.md' --exclude-mail
```suggestion
          lychee -v '**/*.md' --exclude-mail --exclude '.*?ref\=?.*'
```

2021-12-22 21:25 UTC, denis-tingaikin requested changes
Looks overcomplicated.

2021-12-23 09:21 UTC, Mixaster995 commented on .github/workflows/ci.yaml
> +      image: lycheeverse/lychee:latest
ok, fixed

2021-12-23 09:21 UTC, Mixaster995 commented on .github/workflows/ci.yaml
> +          done
ok, fixed

2021-12-23 09:22 UTC, Mixaster995 commented on .github/workflows/ci.yaml
> +          lychee -v '**/*.md' --exclude-mail
ok, fixed

2021-12-23 10:52 UTC, merged