Update refs to the latest tag on Release
networkservicemesh/deployments-k8s pull request #4805
Opened 2022-02-17 12:09 UTC by NikitaSkrynnik

Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>

## Issue
https://github.com/networkservicemesh/deployments-k8s/issues/4804

2022-02-18 09:22 UTC, denis-tingaikin commented on .github/workflows/release.yaml
> +          git push
Can we push to the concrete branch?

2022-02-18 09:24 UTC, denis-tingaikin commented on .github/workflows/release.yaml
> +        id: get-tag-step
Is it possible to reuse it from another job?

2022-02-18 12:54 UTC, denis-tingaikin requested changes

2022-02-18 12:54 UTC, denis-tingaikin commented on .github/workflows/release.yaml
> +          git tag ${{ needs.update-refs.outputs.tag }}
`needs` looks not correct.

```suggestion
          git tag ${{ jobs.update-refs.outputs.tag }}
```

2022-02-18 12:54 UTC, denis-tingaikin commented on .github/workflows/release.yaml
> +          git tag ${{ needs.update-refs.outputs.tag }}
Apply this for other places.

2022-02-24 09:17 UTC, denis-tingaikin commented
@NikitaSkrynnik Could you rebase this?

2022-02-24 09:30 UTC, NikitaSkrynnik commented
@denis-tingaikin, rebase done

2022-02-24 13:09 UTC, glazychev-art approved these changes

2022-03-11 08:58 UTC, denis-tingaikin approved these changes

2022-03-11 08:58 UTC, merged